# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

target 'DanTangSwift' do
  

pod 'Kingfisher', '~> 4.2.0'
pod 'Alamofire', '~> 4.5.1'


end
